name: Build and push

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install -r ci/requirements.txt
        pip install pylint
    - name: Analysing the code with pylint (CI side)
      run: |
        pylint $(git ls-files 'ci/*.py')
    - name: Analysing the code with pylint (server)
      run: |
        pylint $(git ls-files 'server/*.py')

  docker-build-push-ci:
    if: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/tags/' ) }}
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0
        with:
          login-server: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker pack and push
        env:
          REF: ${{ github.ref }}
        working-directory: ./ci
        run: ./docker-pack-push.sh

  docker-build-push-server:
    if: ${{ github.ref == 'refs/heads/main' || startsWith( github.ref, 'refs/tags/' ) }}
    runs-on: ubuntu-latest
    needs: [ lint ]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0
        with:
          login-server: https://index.docker.io/v1/
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: docker pack and push
        env:
          REF: ${{ github.ref }}
        working-directory: ./server
        run: ./docker-pack-push.sh